-- =====================================================================
-- Clothing Shop - MySQL schema & seed data
-- Anh nam tai: src/main/resources/static/images/<loai>/NN.jpg (6 loai, moi loai 10 anh)
-- Chay:  mysql -u root < sql/clothing_shop.sql
-- =====================================================================

CREATE DATABASE IF NOT EXISTS clothing_shop
  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE clothing_shop;

SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS product_images;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS categories;
SET FOREIGN_KEY_CHECKS = 1;

-- ---------- Bang danh muc -----------------------------------------------------
CREATE TABLE categories (
  id          INT AUTO_INCREMENT PRIMARY KEY,
  name        VARCHAR(100) NOT NULL,
  slug        VARCHAR(100) NOT NULL UNIQUE,
  parent_id   INT NULL,                       -- NULL = nhom cha; co gia tri = danh muc con
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_category_parent FOREIGN KEY (parent_id) REFERENCES categories(id)
) ENGINE=InnoDB;

-- ---------- Bang san pham -----------------------------------------------------
CREATE TABLE products (
  id           INT AUTO_INCREMENT PRIMARY KEY,
  category_id  INT NOT NULL,
  name         VARCHAR(150) NOT NULL,
  slug         VARCHAR(150) NOT NULL UNIQUE,
  description  TEXT,
  price        DECIMAL(12,2) NOT NULL,
  stock        INT NOT NULL DEFAULT 0,
  thumbnail    VARCHAR(255),
  created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_product_category
    FOREIGN KEY (category_id) REFERENCES categories(id)
) ENGINE=InnoDB;

-- ---------- Bang anh san pham (gallery) --------------------------------------
CREATE TABLE product_images (
  id          INT AUTO_INCREMENT PRIMARY KEY,
  product_id  INT NOT NULL,
  image_path  VARCHAR(255) NOT NULL,
  sort_order  INT NOT NULL DEFAULT 0,
  CONSTRAINT fk_image_product
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
  CONSTRAINT uq_product_image UNIQUE (product_id, image_path)
) ENGINE=InnoDB;

-- ---------- Bang nguoi dung (khach hang + admin) ----------------------------
-- Dung CREATE ... IF NOT EXISTS va KHONG drop -> chay lai file khong xoa
-- mat khach hang da dang ky. Mat khau luu duoi dang BCrypt hash (app ma hoa).
CREATE TABLE IF NOT EXISTS users (
  id          INT AUTO_INCREMENT PRIMARY KEY,
  full_name   VARCHAR(150) NOT NULL,
  email       VARCHAR(150) NOT NULL UNIQUE,
  password    VARCHAR(255) NOT NULL,
  phone       VARCHAR(20),
  role        VARCHAR(20)  NOT NULL DEFAULT 'CUSTOMER',
  enabled     BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- ---------- Gio hang (moi user 1 gio, moi dong 1 san pham) -------------------
CREATE TABLE IF NOT EXISTS cart_items (
  id          INT AUTO_INCREMENT PRIMARY KEY,
  user_id     INT NOT NULL,
  product_id  INT NOT NULL,
  size        VARCHAR(10) NULL,             -- kich co da chon (S/M/L/XL)
  quantity    INT NOT NULL DEFAULT 1,
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_cart_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT uq_cart_user_product_size UNIQUE (user_id, product_id, size)
) ENGINE=InnoDB;

-- ---------- Don hang ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS orders (
  id             INT AUTO_INCREMENT PRIMARY KEY,
  user_id        INT NOT NULL,
  recipient_name VARCHAR(150) NOT NULL,
  phone          VARCHAR(20)  NOT NULL,
  address        VARCHAR(255) NOT NULL,
  note           VARCHAR(255) NULL,                       -- ghi chu (khong bat buoc)
  payment_method VARCHAR(20)  NOT NULL DEFAULT 'CASH',     -- CASH | BANK
  refund_bank         VARCHAR(100) NULL,                  -- ngan hang nhan hoan tien
  refund_account      VARCHAR(50)  NULL,                  -- so tai khoan nhan hoan tien
  refund_account_name VARCHAR(150) NULL,                  -- chu tai khoan
  total_amount   DECIMAL(12,2) NOT NULL,
  status         VARCHAR(20)  NOT NULL DEFAULT 'PROCESSING',  -- PROCESSING|COMPLETED|REFUNDING|CANCELLED
  created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_order_user FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB;

-- ---------- Chi tiet don hang (snapshot ten + gia luc dat) -------------------
CREATE TABLE IF NOT EXISTS order_items (
  id            INT AUTO_INCREMENT PRIMARY KEY,
  order_id      INT NOT NULL,
  product_id    INT NOT NULL,
  product_name  VARCHAR(150) NOT NULL,
  size          VARCHAR(10) NULL,            -- kich co luc dat (snapshot)
  price         DECIMAL(12,2) NOT NULL,
  quantity      INT NOT NULL,
  CONSTRAINT fk_item_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- =====================================================================
-- Du lieu mau
-- =====================================================================

INSERT INTO categories (id, name, slug, parent_id) VALUES
  (1, 'Áo thun cổ tròn', 'ao-thun-co-tron', NULL),
  (2, 'Áo polo', 'ao-polo', NULL),
  (3, 'Áo sơ mi', 'ao-so-mi', NULL),
  (4, 'Áo khoác', 'ao-khoac', NULL),
  (5, 'Quần short', 'quan-short', NULL),
  (6, 'Quần dài', 'quan-dai', NULL),
  (7, 'Quần jean', 'quan-jean', NULL),
  (8, 'Giày', 'giay', NULL),
  (9, 'Áo Thun Tay Ngắn', 'ao-thun-co-tron-tay-ngan', 1),
  (10, 'Áo Thun Tay Dài', 'ao-thun-tay-dai', 1),
  (11, 'Áo Polo Tay Ngắn', 'ao-thun-co-polo-tay-ngan', 2),
  (12, 'Áo Polo Tay Dài', 'ao-thun-polo-tay-dai', 2),
  (13, 'Áo Sơ Mi Tay Ngắn', 'ao-so-mi-tay-ngan', 3),
  (14, 'Áo Sơ Mi Tay Dài', 'ao-so-mi-tay-dai', 3),
  (15, 'Áo Khoác Jean', 'ao-khoac-jean', 4),
  (16, 'Áo Khoác Kaki', 'ao-khoac-kaki', 4),
  (17, 'Áo Khoác Dù', 'ao-khoac-du', 4),
  (18, 'Quần Short Thun', 'quan-short-thun', 5),
  (19, 'Quần Short Kaki', 'quan-short-kaki', 5),
  (20, 'Quần Tây', 'quan-tay', 6),
  (21, 'Quần Kaki', 'quan-kaki', 6),
  (22, 'Quần Jeans Slim Fit', 'quan-jeans-slimfit', 7),
  (23, 'Quần Jeans Loose Fit', 'quan-jeans-loose-fit', 7),
  (24, 'Giày Oxford', 'giay-oxford', 8),
  (25, 'Giày Loafer', 'giay-loafer', 8),
  (26, 'Giày Boots', 'giay-boots', 8);

INSERT INTO products (id, category_id, name, slug, description, price, stock, thumbnail) VALUES
  (1, 9, 'Áo Thun Sọc Phom Boxy Hack Dáng FlexFit™ Vải Co Giãn Thoáng Mát The No Style 241 Màu Trắng Đen Dáng Rộng Rãi F4', 'ao-thun-co-tron-tay-ngan-01', 'Áo Thun Sọc Phom Boxy Hack Dáng FlexFit™ Vải Co Giãn Thoáng Mát The No Style 241 Màu Trắng Đen Dáng Rộng Rãi F4', 282150, 26, 'images/ao-thun-co-tron-tay-ngan/01.jpg'),
  (2, 9, 'Áo Thun Sọc Phom Boxy Hack Dáng FlexFit™ Vải Co Giãn Thoáng Mát The No Style 241 Màu Đen Trắng Dáng Rộng Rãi F4', 'ao-thun-co-tron-tay-ngan-02', 'Áo Thun Sọc Phom Boxy Hack Dáng FlexFit™ Vải Co Giãn Thoáng Mát The No Style 241 Màu Đen Trắng Dáng Rộng Rãi F4', 282150, 27, 'images/ao-thun-co-tron-tay-ngan/02.jpg'),
  (3, 9, 'Áo Thun Vải Dệt Lưới AirDry™ Thoát Nhiệt Nhanh "PEACE IN EVERY CORNER" The No Style 209 Màu Xanh Lá Đậm Dáng Rộng Rãi F4', 'ao-thun-co-tron-tay-ngan-03', 'Áo Thun Vải Dệt Lưới AirDry™ Thoát Nhiệt Nhanh "PEACE IN EVERY CORNER" The No Style 209 Màu Xanh Lá Đậm Dáng Rộng Rãi F4', 263150, 28, 'images/ao-thun-co-tron-tay-ngan/03.jpg'),
  (4, 9, 'Áo Thun Dệt Lưới AirDry™ Thoát Nhiệt Nhanh "GOLDEN BRIDGE''S EMBRACE" The No Style 208 Màu Đỏ Dáng Rộng Rãi F4', 'ao-thun-co-tron-tay-ngan-04', 'Áo Thun Dệt Lưới AirDry™ Thoát Nhiệt Nhanh "GOLDEN BRIDGE''S EMBRACE" The No Style 208 Màu Đỏ Dáng Rộng Rãi F4', 263150, 29, 'images/ao-thun-co-tron-tay-ngan/04.jpg'),
  (5, 9, 'Áo Thun Vải Dệt Lưới AirDry™ Thoát Nhiệt Nhanh "NEVER SLEEPS" The No Style 207 Màu Xanh Dương Đậm Dáng Rộng Rãi F4', 'ao-thun-co-tron-tay-ngan-05', 'Áo Thun Vải Dệt Lưới AirDry™ Thoát Nhiệt Nhanh "NEVER SLEEPS" The No Style 207 Màu Xanh Dương Đậm Dáng Rộng Rãi F4', 263150, 30, 'images/ao-thun-co-tron-tay-ngan/05.jpg'),
  (6, 9, 'Áo Thun Vải Dệt Lưới AirDry™ Thoát Nhiệt Nhanh "NEVER SLEEPS" The No Style 207 Màu Xám Dáng Rộng Rãi F4', 'ao-thun-co-tron-tay-ngan-06', 'Áo Thun Vải Dệt Lưới AirDry™ Thoát Nhiệt Nhanh "NEVER SLEEPS" The No Style 207 Màu Xám Dáng Rộng Rãi F4', 263150, 31, 'images/ao-thun-co-tron-tay-ngan/06.jpg'),
  (7, 9, 'Áo Thun Dáng Vuông Vai Raglan CloudTouch™ Bề Mặt Êm Ái In Chữ In Nổi The No Style 204 Màu Xám Dáng Rộng Rãi F4', 'ao-thun-co-tron-tay-ngan-07', 'Áo Thun Dáng Vuông Vai Raglan CloudTouch™ Bề Mặt Êm Ái In Chữ In Nổi The No Style 204 Màu Xám Dáng Rộng Rãi F4', 301150, 32, 'images/ao-thun-co-tron-tay-ngan/07.jpg'),
  (8, 9, 'Áo Thun Dáng Vuông Vai Raglan CloudTouch™ Bề Mặt Êm Ái In Chữ In Nổi The No Style 204 Màu Xanh Lá Đậm Dáng Rộng Rãi F4', 'ao-thun-co-tron-tay-ngan-08', 'Áo Thun Dáng Vuông Vai Raglan CloudTouch™ Bề Mặt Êm Ái In Chữ In Nổi The No Style 204 Màu Xanh Lá Đậm Dáng Rộng Rãi F4', 301150, 33, 'images/ao-thun-co-tron-tay-ngan/08.jpg'),
  (9, 9, 'Áo Thun Dáng Vuông Vai Raglan CloudTouch™ Bề Mặt Êm Ái In Chữ In Nổi The No Style 204 Màu Nâu Đậm Dáng Rộng Rãi F4', 'ao-thun-co-tron-tay-ngan-09', 'Áo Thun Dáng Vuông Vai Raglan CloudTouch™ Bề Mặt Êm Ái In Chữ In Nổi The No Style 204 Màu Nâu Đậm Dáng Rộng Rãi F4', 301150, 34, 'images/ao-thun-co-tron-tay-ngan/09.jpg'),
  (10, 9, 'Áo Thun Dáng Vuông Vai Raglan CloudTouch™ Bề Mặt Êm Ái In Chữ In Nổi The No Style 204 Màu Nâu Dáng Rộng Rãi F4', 'ao-thun-co-tron-tay-ngan-10', 'Áo Thun Dáng Vuông Vai Raglan CloudTouch™ Bề Mặt Êm Ái In Chữ In Nổi The No Style 204 Màu Nâu Dáng Rộng Rãi F4', 301150, 35, 'images/ao-thun-co-tron-tay-ngan/10.jpg'),
  (11, 10, 'Áo Thun Tay Dài Raglan FlexFit™ Vải Mỏng Mịn Có Lỗ Xỏ Ngón Tiện Lợi Non Branded 052 Màu Xám Nhạt Dáng Vừa Vặn F3', 'ao-thun-tay-dai-01', 'Áo Thun Tay Dài Raglan FlexFit™ Vải Mỏng Mịn Có Lỗ Xỏ Ngón Tiện Lợi Non Branded 052 Màu Xám Nhạt Dáng Vừa Vặn F3', 234650, 36, 'images/ao-thun-tay-dai/01.jpg'),
  (12, 10, 'Áo Thun Tay Dài Raglan FlexFit™ Vải Mỏng Mịn Có Lỗ Xỏ Ngón Tiện Lợi Non Branded 052 Màu Xanh Dương Dáng Vừa Vặn F3', 'ao-thun-tay-dai-02', 'Áo Thun Tay Dài Raglan FlexFit™ Vải Mỏng Mịn Có Lỗ Xỏ Ngón Tiện Lợi Non Branded 052 Màu Xanh Dương Dáng Vừa Vặn F3', 234650, 37, 'images/ao-thun-tay-dai/02.jpg'),
  (13, 10, 'Áo Thun Tay Dài FlexFit™ Vai Raglan Dễ Vận Động Vải Mỏng Mịn Có Lỗ Xỏ Ngón Tiện Lợi Non Branded 052 Màu Xám Đậm Dáng Vừa Vặn F3', 'ao-thun-tay-dai-03', 'Áo Thun Tay Dài FlexFit™ Vai Raglan Dễ Vận Động Vải Mỏng Mịn Có Lỗ Xỏ Ngón Tiện Lợi Non Branded 052 Màu Xám Đậm Dáng Vừa Vặn F3', 234650, 38, 'images/ao-thun-tay-dai/03.jpg'),
  (14, 10, 'Áo Thun Tay Dài Raglan FlexFit™ Vải Mỏng Mịn Có Lỗ Xỏ Ngón Tiện Lợi Non Branded 052 Màu Xanh Lá Đậm Dáng Vừa Vặn F3', 'ao-thun-tay-dai-04', 'Áo Thun Tay Dài Raglan FlexFit™ Vải Mỏng Mịn Có Lỗ Xỏ Ngón Tiện Lợi Non Branded 052 Màu Xanh Lá Đậm Dáng Vừa Vặn F3', 234650, 39, 'images/ao-thun-tay-dai/04.jpg'),
  (15, 10, 'Áo Thun Tay Dài Raglan FlexFit™ Vải Mỏng Mịn Có Lỗ Xỏ Ngón Tiện Lợi Non Branded 052 Màu Xanh Dương Đậm Dáng Vừa Vặn F3', 'ao-thun-tay-dai-05', 'Áo Thun Tay Dài Raglan FlexFit™ Vải Mỏng Mịn Có Lỗ Xỏ Ngón Tiện Lợi Non Branded 052 Màu Xanh Dương Đậm Dáng Vừa Vặn F3', 234650, 40, 'images/ao-thun-tay-dai/05.jpg'),
  (16, 10, 'Áo Thun Tay Dài Raglan FlexFit™ Vải Mỏng Mịn Có Lỗ Xỏ Ngón Tiện Lợi Non Branded 052 Màu Trắng Dáng Vừa Vặn F3', 'ao-thun-tay-dai-06', 'Áo Thun Tay Dài Raglan FlexFit™ Vải Mỏng Mịn Có Lỗ Xỏ Ngón Tiện Lợi Non Branded 052 Màu Trắng Dáng Vừa Vặn F3', 234650, 41, 'images/ao-thun-tay-dai/06.jpg'),
  (17, 10, 'Áo Thun Tay Dài Raglan FlexFit™ Vải Mỏng Mịn Có Lỗ Xỏ Ngón Tiện Lợi Non Branded 052 Màu Đen Dáng Vừa Vặn F3', 'ao-thun-tay-dai-07', 'Áo Thun Tay Dài Raglan FlexFit™ Vải Mỏng Mịn Có Lỗ Xỏ Ngón Tiện Lợi Non Branded 052 Màu Đen Dáng Vừa Vặn F3', 234650, 42, 'images/ao-thun-tay-dai/07.jpg'),
  (18, 10, 'Áo Thun Tay FlexFit™ Co Giãn Tốt Khoe Dáng Khỏe Khoắn Non Branded 049 Màu Xám Đậm Dáng Ôm Vừa F2', 'ao-thun-tay-dai-08', 'Áo Thun Tay FlexFit™ Co Giãn Tốt Khoe Dáng Khỏe Khoắn Non Branded 049 Màu Xám Đậm Dáng Ôm Vừa F2', 234650, 43, 'images/ao-thun-tay-dai/08.jpg'),
  (19, 10, 'Áo Thun Tay FlexFit™ Co Giãn Tốt Khoe Dáng Khỏe Khoắn Non Branded 049 Màu Nâu Dáng Ôm Vừa F2', 'ao-thun-tay-dai-09', 'Áo Thun Tay FlexFit™ Co Giãn Tốt Khoe Dáng Khỏe Khoắn Non Branded 049 Màu Nâu Dáng Ôm Vừa F2', 234650, 44, 'images/ao-thun-tay-dai/09.jpg'),
  (20, 10, 'Áo Thun Tay FlexFit™ Co Giãn Tốt Khoe Dáng Khỏe Khoắn Non Branded 049 Màu Be Dáng Ôm Vừa F2', 'ao-thun-tay-dai-10', 'Áo Thun Tay FlexFit™ Co Giãn Tốt Khoe Dáng Khỏe Khoắn Non Branded 049 Màu Be Dáng Ôm Vừa F2', 234650, 45, 'images/ao-thun-tay-dai/10.jpg'),
  (21, 11, 'Áo Polo Sọc Boxy FlexFit™ Vải Co Giãn Túi Xếp Origami The No Style 245 Màu Trắng 11 Dáng Hộp F5', 'ao-thun-co-polo-tay-ngan-01', 'Áo Polo Sọc Boxy FlexFit™ Vải Co Giãn Túi Xếp Origami The No Style 245 Màu Trắng 11 Dáng Hộp F5', 427000, 46, 'images/ao-thun-co-polo-tay-ngan/01.jpg'),
  (22, 11, 'Áo Polo Sọc Boxy FlexFit™ Vải Co Giãn Túi Xếp Origami The No Style 245 Màu Đen 99 Dáng Hộp F5', 'ao-thun-co-polo-tay-ngan-02', 'Áo Polo Sọc Boxy FlexFit™ Vải Co Giãn Túi Xếp Origami The No Style 245 Màu Đen 99 Dáng Hộp F5', 427000, 47, 'images/ao-thun-co-polo-tay-ngan/02.jpg'),
  (23, 11, 'Áo Polo Boxy Hack Dáng Che Bụng CloudTouch™ Cổ Áo Bản Lớn Cá Tính The No Style 249 Rêu 76 Dáng Hộp F5', 'ao-thun-co-polo-tay-ngan-03', 'Áo Polo Boxy Hack Dáng Che Bụng CloudTouch™ Cổ Áo Bản Lớn Cá Tính The No Style 249 Rêu 76 Dáng Hộp F5', 377150, 48, 'images/ao-thun-co-polo-tay-ngan/03.jpg'),
  (24, 11, 'Áo Polo Boxy Hack Dáng Che Bụng CloudTouch™ Cổ Áo Bản Lớn Cá Tính The No Style 249 Rêu 72 Dáng Hộp F5', 'ao-thun-co-polo-tay-ngan-04', 'Áo Polo Boxy Hack Dáng Che Bụng CloudTouch™ Cổ Áo Bản Lớn Cá Tính The No Style 249 Rêu 72 Dáng Hộp F5', 377150, 49, 'images/ao-thun-co-polo-tay-ngan/04.jpg'),
  (25, 11, 'Áo Polo Boxy Hack Dáng Che Bụng CloudTouch™ Cổ Áo Bản Lớn Cá Tính The No Style 249 Cam 43 Dáng Hộp F5', 'ao-thun-co-polo-tay-ngan-05', 'Áo Polo Boxy Hack Dáng Che Bụng CloudTouch™ Cổ Áo Bản Lớn Cá Tính The No Style 249 Cam 43 Dáng Hộp F5', 377150, 50, 'images/ao-thun-co-polo-tay-ngan/05.jpg'),
  (26, 11, 'Áo Polo Boxy Hack Dáng Che Bụng CloudTouch™ Cổ Áo Bản Lớn Cá Tính The No Style 249 Beige 28 Dáng Hộp F5', 'ao-thun-co-polo-tay-ngan-06', 'Áo Polo Boxy Hack Dáng Che Bụng CloudTouch™ Cổ Áo Bản Lớn Cá Tính The No Style 249 Beige 28 Dáng Hộp F5', 377150, 51, 'images/ao-thun-co-polo-tay-ngan/06.jpg'),
  (27, 11, 'Áo Polo Boxy Hack Dáng Che Bụng CloudTouch™ Cổ Áo Bản Lớn Cá Tính The No Style 249 Beige 21 Dáng Hộp F5', 'ao-thun-co-polo-tay-ngan-07', 'Áo Polo Boxy Hack Dáng Che Bụng CloudTouch™ Cổ Áo Bản Lớn Cá Tính The No Style 249 Beige 21 Dáng Hộp F5', 377150, 52, 'images/ao-thun-co-polo-tay-ngan/07.jpg'),
  (28, 11, 'Áo Polo Cổ Khóa Kéo ColorLock™ Vải Cá Sấu Thoáng Mát Khóa Màu Sâu The Weekend 008 Màu Xanh Dương Trắng Dáng Vừa Vặn F3', 'ao-thun-co-polo-tay-ngan-08', 'Áo Polo Cổ Khóa Kéo ColorLock™ Vải Cá Sấu Thoáng Mát Khóa Màu Sâu The Weekend 008 Màu Xanh Dương Trắng Dáng Vừa Vặn F3', 434150, 53, 'images/ao-thun-co-polo-tay-ngan/08.jpg'),
  (29, 11, 'Áo Polo Cổ Khóa Kéo ColorLock™ Vải Cá Sấu Thoáng Mát Khóa Màu Sâu The Weekend 008 Màu Trắng Xanh Dương Dáng Vừa Vặn F3', 'ao-thun-co-polo-tay-ngan-09', 'Áo Polo Cổ Khóa Kéo ColorLock™ Vải Cá Sấu Thoáng Mát Khóa Màu Sâu The Weekend 008 Màu Trắng Xanh Dương Dáng Vừa Vặn F3', 434150, 54, 'images/ao-thun-co-polo-tay-ngan/09.jpg'),
  (30, 11, 'Áo Polo Khóa Kéo ColorLock™ Vải Thoát Nhiệt Vải Chống Lem Màu The Weekend 006 Màu Trắng Xanh Dương Dáng Vừa Vặn F3', 'ao-thun-co-polo-tay-ngan-10', 'Áo Polo Khóa Kéo ColorLock™ Vải Thoát Nhiệt Vải Chống Lem Màu The Weekend 006 Màu Trắng Xanh Dương Dáng Vừa Vặn F3', 434150, 25, 'images/ao-thun-co-polo-tay-ngan/10.jpg'),
  (31, 12, 'Áo Polo Tay Dài Khóa Kéo DurableTex™ Mềm Mại Nịnh Da Lên Dáng Chuẩn The Weekend 042 Màu Đen Dáng Rộng Rãi F4', 'ao-thun-polo-tay-dai-01', 'Áo Polo Tay Dài Khóa Kéo DurableTex™ Mềm Mại Nịnh Da Lên Dáng Chuẩn The Weekend 042 Màu Đen Dáng Rộng Rãi F4', 377150, 26, 'images/ao-thun-polo-tay-dai/01.jpg'),
  (32, 12, 'Áo Polo Tay Dài Khóa Kéo DurableTex™ Mềm Mại Nịnh Da Lên Dáng Chuẩn The Weekend 042 Màu Xám Đậm Dáng Rộng Rãi F4', 'ao-thun-polo-tay-dai-02', 'Áo Polo Tay Dài Khóa Kéo DurableTex™ Mềm Mại Nịnh Da Lên Dáng Chuẩn The Weekend 042 Màu Xám Đậm Dáng Rộng Rãi F4', 377150, 27, 'images/ao-thun-polo-tay-dai/02.jpg'),
  (33, 12, 'Áo Polo Tay Dài Khóa Kéo DurableTex™ Mềm Mại Nịnh Da Lên Dáng Chuẩn The Weekend 042 Màu Be Dáng Rộng Rãi F4', 'ao-thun-polo-tay-dai-03', 'Áo Polo Tay Dài Khóa Kéo DurableTex™ Mềm Mại Nịnh Da Lên Dáng Chuẩn The Weekend 042 Màu Be Dáng Rộng Rãi F4', 377150, 28, 'images/ao-thun-polo-tay-dai/03.jpg'),
  (34, 12, 'Áo Polo Tay Dài Khóa Kéo DurableTex™ Mềm Mại Nịnh Da Lên Dáng Chuẩn The Weekend 042 Màu Xanh Dương Đậm Dáng Rộng Rãi F4', 'ao-thun-polo-tay-dai-04', 'Áo Polo Tay Dài Khóa Kéo DurableTex™ Mềm Mại Nịnh Da Lên Dáng Chuẩn The Weekend 042 Màu Xanh Dương Đậm Dáng Rộng Rãi F4', 377150, 29, 'images/ao-thun-polo-tay-dai/04.jpg'),
  (35, 12, 'Áo Polo Tay Dài Cotton Phối Màu The No Style 181 Màu Đen Be Dáng Rộng Rãi F4', 'ao-thun-polo-tay-dai-05', 'Áo Polo Tay Dài Cotton Phối Màu The No Style 181 Màu Đen Be Dáng Rộng Rãi F4', 178500, 30, 'images/ao-thun-polo-tay-dai/05.jpg'),
  (36, 12, 'Áo Polo Tay Dài Cotton Phối Màu The No Style 181 Màu Nâu Be Dáng Rộng Rãi F4', 'ao-thun-polo-tay-dai-06', 'Áo Polo Tay Dài Cotton Phối Màu The No Style 181 Màu Nâu Be Dáng Rộng Rãi F4', 178500, 31, 'images/ao-thun-polo-tay-dai/06.jpg'),
  (37, 12, 'Áo Polo Tay Dài Vải Thoát Khí Cổ Phối Màu Seventy Seven 020 Màu Xám Dáng Ôm Vừa F2', 'ao-thun-polo-tay-dai-07', 'Áo Polo Tay Dài Vải Thoát Khí Cổ Phối Màu Seventy Seven 020 Màu Xám Dáng Ôm Vừa F2', 128500, 32, 'images/ao-thun-polo-tay-dai/07.jpg'),
  (38, 12, 'Áo Polo Tay Dài Vải Thoát Khí Cổ Phối Màu Seventy Seven 020 Màu Xanh Dương Đậm Dáng Ôm Vừa F2', 'ao-thun-polo-tay-dai-08', 'Áo Polo Tay Dài Vải Thoát Khí Cổ Phối Màu Seventy Seven 020 Màu Xanh Dương Đậm Dáng Ôm Vừa F2', 128500, 33, 'images/ao-thun-polo-tay-dai/08.jpg'),
  (39, 12, 'Áo Polo Tay Dài Vải Thoát Khí Cổ Phối Màu Seventy Seven 020 Màu Trắng Dáng Ôm Vừa F2', 'ao-thun-polo-tay-dai-09', 'Áo Polo Tay Dài Vải Thoát Khí Cổ Phối Màu Seventy Seven 020 Màu Trắng Dáng Ôm Vừa F2', 128500, 34, 'images/ao-thun-polo-tay-dai/09.jpg'),
  (40, 12, 'Áo Polo Tay Dài Vải Thoát Khí Cổ Phối Màu Seventy Seven 020 Màu Đen Dáng Ôm Vừa F2', 'ao-thun-polo-tay-dai-10', 'Áo Polo Tay Dài Vải Thoát Khí Cổ Phối Màu Seventy Seven 020 Màu Đen Dáng Ôm Vừa F2', 128500, 35, 'images/ao-thun-polo-tay-dai/10.jpg'),
  (41, 13, 'Sơ Mi Tay Ngắn Boxy EasyCare™ Vải Oxford Mềm Thoáng Tay Lật Lai Sọc Trendy The Weekend 048 Màu Xám Trắng 19 Dáng Hộp F5', 'ao-so-mi-tay-ngan-01', 'Sơ Mi Tay Ngắn Boxy EasyCare™ Vải Oxford Mềm Thoáng Tay Lật Lai Sọc Trendy The Weekend 048 Màu Xám Trắng 19 Dáng Hộp F5', 310650, 36, 'images/ao-so-mi-tay-ngan/01.jpg'),
  (42, 13, 'Sơ Mi Tay Ngắn Boxy EasyCare™ Vải Oxford Mềm Thoáng Tay Lật Lai Sọc Trendy The Weekend 048 Màu Trắng 10 Dáng Hộp F5', 'ao-so-mi-tay-ngan-02', 'Sơ Mi Tay Ngắn Boxy EasyCare™ Vải Oxford Mềm Thoáng Tay Lật Lai Sọc Trendy The Weekend 048 Màu Trắng 10 Dáng Hộp F5', 310650, 37, 'images/ao-so-mi-tay-ngan/02.jpg'),
  (43, 13, 'Sơ Mi Tay Ngắn Boxy EasyCare™ Vải Oxford Mềm Thoáng Tay Lật Lai Sọc Trendy The Weekend 048 Màu Đen 99 Dáng Hộp F5', 'ao-so-mi-tay-ngan-03', 'Sơ Mi Tay Ngắn Boxy EasyCare™ Vải Oxford Mềm Thoáng Tay Lật Lai Sọc Trendy The Weekend 048 Màu Đen 99 Dáng Hộp F5', 310650, 38, 'images/ao-so-mi-tay-ngan/03.jpg'),
  (44, 13, 'Sơ Mi Tay Ngắn Boxy EasyCare™ Vải Oxford Mềm Thoáng Tay Lật Lai Sọc Trendy The Weekend 048 Màu Beige 63 Dáng Hộp F5', 'ao-so-mi-tay-ngan-04', 'Sơ Mi Tay Ngắn Boxy EasyCare™ Vải Oxford Mềm Thoáng Tay Lật Lai Sọc Trendy The Weekend 048 Màu Beige 63 Dáng Hộp F5', 310650, 39, 'images/ao-so-mi-tay-ngan/04.jpg'),
  (45, 13, 'Áo Sơ Mi Tay Ngắn Họa Tiết Sọc AirDry™ Mịn Mướt Nhẹ Mát The No Style 203 Màu Trắng Xanh Dương Dáng Vừa Vặn F3', 'ao-so-mi-tay-ngan-05', 'Áo Sơ Mi Tay Ngắn Họa Tiết Sọc AirDry™ Mịn Mướt Nhẹ Mát The No Style 203 Màu Trắng Xanh Dương Dáng Vừa Vặn F3', 377150, 40, 'images/ao-so-mi-tay-ngan/05.jpg'),
  (46, 13, 'Áo Sơ Mi Tay Ngắn Họa Tiết Sọc AirDry™ Mịn Mướt Nhẹ Mát The No Style 203 Màu Trắng Xanh Lá Dáng Vừa Vặn F3', 'ao-so-mi-tay-ngan-06', 'Áo Sơ Mi Tay Ngắn Họa Tiết Sọc AirDry™ Mịn Mướt Nhẹ Mát The No Style 203 Màu Trắng Xanh Lá Dáng Vừa Vặn F3', 377150, 41, 'images/ao-so-mi-tay-ngan/06.jpg'),
  (47, 13, 'Áo Sơ Mi Tay Ngắn Vải Xước Như Linen AirDry™ Mịn Mặc Mát Giải Nhiệt Mùa Hè The No Style 216 Màu Đen Dáng Vừa Vặn F3', 'ao-so-mi-tay-ngan-07', 'Áo Sơ Mi Tay Ngắn Vải Xước Như Linen AirDry™ Mịn Mặc Mát Giải Nhiệt Mùa Hè The No Style 216 Màu Đen Dáng Vừa Vặn F3', 282150, 42, 'images/ao-so-mi-tay-ngan/07.jpg'),
  (48, 13, 'Áo Sơ Mi Tay Ngắn Vải Xước Như Linen AirDry™ Mịn Mặc Mát Giải Nhiệt Mùa Hè The No Style 216 Màu Nâu Nhạt Dáng Vừa Vặn F3', 'ao-so-mi-tay-ngan-08', 'Áo Sơ Mi Tay Ngắn Vải Xước Như Linen AirDry™ Mịn Mặc Mát Giải Nhiệt Mùa Hè The No Style 216 Màu Nâu Nhạt Dáng Vừa Vặn F3', 282150, 43, 'images/ao-so-mi-tay-ngan/08.jpg'),
  (49, 13, 'Áo Sơ Mi Tay Ngắn Giấu Bụng DurableTex™ Vải Dày Dặn Đứng Form Multi Color Jean 003 Màu Nâu Đậm Dáng Rộng Rãi F4', 'ao-so-mi-tay-ngan-09', 'Áo Sơ Mi Tay Ngắn Giấu Bụng DurableTex™ Vải Dày Dặn Đứng Form Multi Color Jean 003 Màu Nâu Đậm Dáng Rộng Rãi F4', 405650, 44, 'images/ao-so-mi-tay-ngan/09.jpg'),
  (50, 13, 'Áo Sơ Mi Tay Ngắn Giấu Bụng DurableTex™ Vải Dày Dặn Đứng Form Multi Color Jean 003 Màu Trắng Dáng Rộng Rãi F4', 'ao-so-mi-tay-ngan-10', 'Áo Sơ Mi Tay Ngắn Giấu Bụng DurableTex™ Vải Dày Dặn Đứng Form Multi Color Jean 003 Màu Trắng Dáng Rộng Rãi F4', 405650, 45, 'images/ao-so-mi-tay-ngan/10.jpg'),
  (51, 14, 'Sơ Mi Công Sở Tay Dài AirDry™ Nhẹ Co Giãn Thoát Nhiệt Tốt Seventy Seven 052 Màu Xanh Dương Nhạt Dáng Dáng Ôm Vừa F2', 'ao-so-mi-tay-dai-01', 'Sơ Mi Công Sở Tay Dài AirDry™ Nhẹ Co Giãn Thoát Nhiệt Tốt Seventy Seven 052 Màu Xanh Dương Nhạt Dáng Dáng Ôm Vừa F2', 397000, 46, 'images/ao-so-mi-tay-dai/01.jpg'),
  (52, 14, 'Sơ Mi Công Sở Tay Dài AirDry™ Nhẹ Co Giãn Thoát Nhiệt Tốt Seventy Seven 052 Màu Xanh Dương Đậm Dáng Dáng Ôm Vừa F2', 'ao-so-mi-tay-dai-02', 'Sơ Mi Công Sở Tay Dài AirDry™ Nhẹ Co Giãn Thoát Nhiệt Tốt Seventy Seven 052 Màu Xanh Dương Đậm Dáng Dáng Ôm Vừa F2', 397000, 47, 'images/ao-so-mi-tay-dai/02.jpg'),
  (53, 14, 'Sơ Mi Công Sở Tay Dài AirDry™ Nhẹ Co Giãn Thoát Nhiệt Tốt Seventy Seven 052 Màu Trắng Dáng Dáng Ôm Vừa F2', 'ao-so-mi-tay-dai-03', 'Sơ Mi Công Sở Tay Dài AirDry™ Nhẹ Co Giãn Thoát Nhiệt Tốt Seventy Seven 052 Màu Trắng Dáng Dáng Ôm Vừa F2', 397000, 48, 'images/ao-so-mi-tay-dai/03.jpg'),
  (54, 14, 'Sơ Mi Công Sở Tay Dài AirDry™ Nhẹ Co Giãn Thoát Nhiệt Tốt Seventy Seven 052 Màu Đen Dáng Dáng Ôm Vừa F2', 'ao-so-mi-tay-dai-04', 'Sơ Mi Công Sở Tay Dài AirDry™ Nhẹ Co Giãn Thoát Nhiệt Tốt Seventy Seven 052 Màu Đen Dáng Dáng Ôm Vừa F2', 397000, 49, 'images/ao-so-mi-tay-dai/04.jpg'),
  (55, 14, 'Áo Sơ Mi Tay Dài Công Sở AirDry™ Vải Sọc Siêu Nhẹ Thoáng The Minimalist 017 Màu Xanh Dương Nhạt Dáng Vừa Vặn F3', 'ao-so-mi-tay-dai-05', 'Áo Sơ Mi Tay Dài Công Sở AirDry™ Vải Sọc Siêu Nhẹ Thoáng The Minimalist 017 Màu Xanh Dương Nhạt Dáng Vừa Vặn F3', 377150, 50, 'images/ao-so-mi-tay-dai/05.jpg'),
  (56, 14, 'Áo Sơ Mi Tay Dài Công Sở AirDry™ Vải Sọc Siêu Nhẹ Thoáng The Minimalist 017 Màu Xanh Dương Dáng Vừa Vặn F3', 'ao-so-mi-tay-dai-06', 'Áo Sơ Mi Tay Dài Công Sở AirDry™ Vải Sọc Siêu Nhẹ Thoáng The Minimalist 017 Màu Xanh Dương Dáng Vừa Vặn F3', 377150, 51, 'images/ao-so-mi-tay-dai/06.jpg'),
  (57, 14, 'Áo Sơ Mi Tay Dài Công Sở AirDry™ Vải Sọc Siêu Nhẹ Thoáng The Minimalist 017 Màu Xám Nhạt Dáng Vừa Vặn F3', 'ao-so-mi-tay-dai-07', 'Áo Sơ Mi Tay Dài Công Sở AirDry™ Vải Sọc Siêu Nhẹ Thoáng The Minimalist 017 Màu Xám Nhạt Dáng Vừa Vặn F3', 377150, 52, 'images/ao-so-mi-tay-dai/07.jpg'),
  (58, 14, 'Áo Sơ Mi Tay Dài Công Sở AirDry™ Vải Sọc Siêu Nhẹ Thoáng The Minimalist 017 Màu Nâu Nhạt Dáng Vừa Vặn F3', 'ao-so-mi-tay-dai-08', 'Áo Sơ Mi Tay Dài Công Sở AirDry™ Vải Sọc Siêu Nhẹ Thoáng The Minimalist 017 Màu Nâu Nhạt Dáng Vừa Vặn F3', 377150, 53, 'images/ao-so-mi-tay-dai/08.jpg'),
  (59, 14, 'Áo Sơ Mi Tay Dài Công Sở AirDry™ Vải Sọc Siêu Nhẹ Thoáng The Minimalist 017 Màu Hồng Dáng Vừa Vặn F3', 'ao-so-mi-tay-dai-09', 'Áo Sơ Mi Tay Dài Công Sở AirDry™ Vải Sọc Siêu Nhẹ Thoáng The Minimalist 017 Màu Hồng Dáng Vừa Vặn F3', 377150, 54, 'images/ao-so-mi-tay-dai/09.jpg'),
  (60, 14, 'Áo Sơ Mi Tay Dài RainShield™ Vải Trượt Nước Mặc Nhẹ Bền Bỉ The Minimalist 024 Màu Xám Nhạt Dáng Vừa Vặn F3', 'ao-so-mi-tay-dai-10', 'Áo Sơ Mi Tay Dài RainShield™ Vải Trượt Nước Mặc Nhẹ Bền Bỉ The Minimalist 024 Màu Xám Nhạt Dáng Vừa Vặn F3', 339150, 25, 'images/ao-so-mi-tay-dai/10.jpg'),
  (61, 15, 'Áo Khoác Jean ColorLock™ Khóa Màu Đen Siêu Bền Tek Black Jean 003 Màu Đen Dáng Vừa Vặn F3', 'ao-khoac-jean-01', 'Áo Khoác Jean ColorLock™ Khóa Màu Đen Siêu Bền Tek Black Jean 003 Màu Đen Dáng Vừa Vặn F3', 757150, 26, 'images/ao-khoac-jean/01.jpg'),
  (62, 15, 'Áo Khoác Jean ColorLock™ Giữ Màu Đen Sâu Lâu Bạc Màu Tek Black Jean 002 Màu Đen Dáng Vừa Vặn F3', 'ao-khoac-jean-02', 'Áo Khoác Jean ColorLock™ Giữ Màu Đen Sâu Lâu Bạc Màu Tek Black Jean 002 Màu Đen Dáng Vừa Vặn F3', 662150, 27, 'images/ao-khoac-jean/02.jpg'),
  (63, 15, 'Áo Khoác Jean Kiểu Cổ Điển DurableTex™ Vải Dày Dặn Bền Chắc Multi Color Jean 004 Màu Xanh Dương Đậm Dáng Vừa Vặn F3', 'ao-khoac-jean-03', 'Áo Khoác Jean Kiểu Cổ Điển DurableTex™ Vải Dày Dặn Bền Chắc Multi Color Jean 004 Màu Xanh Dương Đậm Dáng Vừa Vặn F3', 757150, 28, 'images/ao-khoac-jean/03.jpg'),
  (64, 15, 'Áo Khoác Jean Kiểu Cổ Điển DurableTex™ Vải Dày Dặn Bền Chắc Multi Color Jean 004 Màu Nâu Dáng Vừa Vặn F3', 'ao-khoac-jean-04', 'Áo Khoác Jean Kiểu Cổ Điển DurableTex™ Vải Dày Dặn Bền Chắc Multi Color Jean 004 Màu Nâu Dáng Vừa Vặn F3', 757150, 29, 'images/ao-khoac-jean/04.jpg'),
  (65, 15, 'Áo Khoác Jean Kiểu Cổ Điển DurableTex™ Vải Dày Dặn Bền Chắc Multi Color Jean 004 Màu Xám Đậm Dáng Vừa Vặn F3', 'ao-khoac-jean-05', 'Áo Khoác Jean Kiểu Cổ Điển DurableTex™ Vải Dày Dặn Bền Chắc Multi Color Jean 004 Màu Xám Đậm Dáng Vừa Vặn F3', 757150, 30, 'images/ao-khoac-jean/05.jpg'),
  (66, 15, 'Áo Khoác Jean DurableTex™ Chất Vải Đanh Chắc Mặc Bền The Original 001 Màu Xanh Dương Đậm Dáng Vừa Vặn F3', 'ao-khoac-jean-06', 'Áo Khoác Jean DurableTex™ Chất Vải Đanh Chắc Mặc Bền The Original 001 Màu Xanh Dương Đậm Dáng Vừa Vặn F3', 529150, 31, 'images/ao-khoac-jean/06.jpg'),
  (67, 15, 'Áo Khoác Jean Bụi Bặm DurableTex™ Cản Gió Che Nắng Tốt Multi Color Jean 011 Màu Be Dáng Vừa Vặn F3', 'ao-khoac-jean-07', 'Áo Khoác Jean Bụi Bặm DurableTex™ Cản Gió Che Nắng Tốt Multi Color Jean 011 Màu Be Dáng Vừa Vặn F3', 567150, 32, 'images/ao-khoac-jean/07.jpg'),
  (68, 15, 'Áo Khoác Jean Bụi Bặm DurableTex™ Cản Gió Che Nắng Tốt Multi Color Jean 011 Màu Xám Đậm Dáng Vừa Vặn F3', 'ao-khoac-jean-08', 'Áo Khoác Jean Bụi Bặm DurableTex™ Cản Gió Che Nắng Tốt Multi Color Jean 011 Màu Xám Đậm Dáng Vừa Vặn F3', 567150, 33, 'images/ao-khoac-jean/08.jpg'),
  (69, 15, 'Áo Khoác Jean Bụi Bặm DurableTex™ Cản Gió Che Nắng Tốt Multi Color Jean 011 Màu Nâu Đậm Dáng Vừa Vặn F3', 'ao-khoac-jean-09', 'Áo Khoác Jean Bụi Bặm DurableTex™ Cản Gió Che Nắng Tốt Multi Color Jean 011 Màu Nâu Đậm Dáng Vừa Vặn F3', 567150, 34, 'images/ao-khoac-jean/09.jpg'),
  (70, 15, 'Áo Khoác Jean Bụi Bặm DurableTex™ Cản Gió Che Nắng Tốt Multi Color Jean 011 Màu Xanh Lá Đậm Dáng Vừa Vặn F3', 'ao-khoac-jean-10', 'Áo Khoác Jean Bụi Bặm DurableTex™ Cản Gió Che Nắng Tốt Multi Color Jean 011 Màu Xanh Lá Đậm Dáng Vừa Vặn F3', 567150, 35, 'images/ao-khoac-jean/10.jpg'),
  (71, 16, 'Áo Khoác Kaki DurableTex™ Vải Cotton Dày Dặn Chắn Gió Cản Bụi The Worker 011 Màu Xám Nhạt Dáng Vừa Vặn F3', 'ao-khoac-kaki-01', 'Áo Khoác Kaki DurableTex™ Vải Cotton Dày Dặn Chắn Gió Cản Bụi The Worker 011 Màu Xám Nhạt Dáng Vừa Vặn F3', 757150, 36, 'images/ao-khoac-kaki/01.jpg'),
  (72, 16, 'Áo Khoác Kaki DurableTex™ Vải Cotton Dày Dặn Chắn Gió Cản Bụi The Worker 011 Màu Đen Dáng Vừa Vặn F3', 'ao-khoac-kaki-02', 'Áo Khoác Kaki DurableTex™ Vải Cotton Dày Dặn Chắn Gió Cản Bụi The Worker 011 Màu Đen Dáng Vừa Vặn F3', 757150, 37, 'images/ao-khoac-kaki/02.jpg'),
  (73, 16, 'Áo Khoác Kaki DurableTex™ Vải Cotton Dày Dặn Chắn Gió Cản Bụi The Worker 011 Màu Xanh Lá Đậm Dáng Vừa Vặn F3', 'ao-khoac-kaki-03', 'Áo Khoác Kaki DurableTex™ Vải Cotton Dày Dặn Chắn Gió Cản Bụi The Worker 011 Màu Xanh Lá Đậm Dáng Vừa Vặn F3', 757150, 38, 'images/ao-khoac-kaki/03.jpg'),
  (74, 16, 'Áo Khoác Kaki Bụi Bặm DurableTex™ Dày Dặn Mặc Bền Phối Màu Ở Cổ The Worker 001 Màu Xanh Dương Đậm Dáng Vừa Vặn F3', 'ao-khoac-kaki-04', 'Áo Khoác Kaki Bụi Bặm DurableTex™ Dày Dặn Mặc Bền Phối Màu Ở Cổ The Worker 001 Màu Xanh Dương Đậm Dáng Vừa Vặn F3', 567150, 39, 'images/ao-khoac-kaki/04.jpg'),
  (75, 16, 'Áo Khoác Kaki Bụi Bặm DurableTex™ Dày Dặn Mặc Bền Phối Màu Ở Cổ The Worker 001 Màu Nâu Đậm Dáng Vừa Vặn F3', 'ao-khoac-kaki-05', 'Áo Khoác Kaki Bụi Bặm DurableTex™ Dày Dặn Mặc Bền Phối Màu Ở Cổ The Worker 001 Màu Nâu Đậm Dáng Vừa Vặn F3', 567150, 40, 'images/ao-khoac-kaki/05.jpg'),
  (76, 16, 'Áo Khoác Kaki Nhung Dày Dặn Giữ Ấm Chống Nắng The No Style 190 Màu Nâu Đậm Dáng Rộng Rãi F4', 'ao-khoac-kaki-06', 'Áo Khoác Kaki Nhung Dày Dặn Giữ Ấm Chống Nắng The No Style 190 Màu Nâu Đậm Dáng Rộng Rãi F4', 298500, 41, 'images/ao-khoac-kaki/06.jpg'),
  (77, 16, 'Áo Khoác Nhung Tăm Cổ Điển DurableTex™ Vải Đanh Chắc Ít Nhăn Seventy Seven 037 Màu Be Dáng Rộng Rãi F4', 'ao-khoac-kaki-07', 'Áo Khoác Nhung Tăm Cổ Điển DurableTex™ Vải Đanh Chắc Ít Nhăn Seventy Seven 037 Màu Be Dáng Rộng Rãi F4', 197000, 42, 'images/ao-khoac-kaki/07.jpg'),
  (78, 16, 'Áo Khoác Nhung Tăm Cổ Điển DurableTex™ Vải Đanh Chắc Ít Nhăn Seventy Seven 037 Màu Xanh Lá Đậm Dáng Rộng Rãi F4', 'ao-khoac-kaki-08', 'Áo Khoác Nhung Tăm Cổ Điển DurableTex™ Vải Đanh Chắc Ít Nhăn Seventy Seven 037 Màu Xanh Lá Đậm Dáng Rộng Rãi F4', 197000, 43, 'images/ao-khoac-kaki/08.jpg'),
  (79, 16, 'Áo Khoác Nhung Tăm Cổ Điển DurableTex™ Vải Đanh Chắc Ít Nhăn Seventy Seven 037 Màu Xanh Ngọc Nhạt Dáng Rộng Rãi F4', 'ao-khoac-kaki-09', 'Áo Khoác Nhung Tăm Cổ Điển DurableTex™ Vải Đanh Chắc Ít Nhăn Seventy Seven 037 Màu Xanh Ngọc Nhạt Dáng Rộng Rãi F4', 197000, 44, 'images/ao-khoac-kaki/09.jpg'),
  (80, 16, 'Áo Khoác Nhung Tăm Cổ Điển DurableTex™ Vải Đanh Chắc Ít Nhăn Seventy Seven 037 Màu Đen Dáng Rộng Rãi F4', 'ao-khoac-kaki-10', 'Áo Khoác Nhung Tăm Cổ Điển DurableTex™ Vải Đanh Chắc Ít Nhăn Seventy Seven 037 Màu Đen Dáng Rộng Rãi F4', 197000, 45, 'images/ao-khoac-kaki/10.jpg'),
  (81, 17, 'Áo Khoác Dù Nhẹ DurableTex™ Nhanh Khô Che Nắng Chắn Gió Tiện Lợi Seventy Seven 040 Màu Đen Dáng Vừa Vặn F3', 'ao-khoac-du-01', 'Áo Khoác Dù Nhẹ DurableTex™ Nhanh Khô Che Nắng Chắn Gió Tiện Lợi Seventy Seven 040 Màu Đen Dáng Vừa Vặn F3', 197000, 46, 'images/ao-khoac-du/01.jpg'),
  (82, 17, 'Áo Khoác Dù Phối Màu DurableTex™ Nhanh Khô Kiểu Dáng Thể Thao The No Style 058 Màu Xanh Lá Đậm Dáng Vừa Vặn F3', 'ao-khoac-du-02', 'Áo Khoác Dù Phối Màu DurableTex™ Nhanh Khô Kiểu Dáng Thể Thao The No Style 058 Màu Xanh Lá Đậm Dáng Vừa Vặn F3', 447000, 47, 'images/ao-khoac-du/02.jpg'),
  (83, 17, 'Áo Khoác Dù Phối Màu DurableTex™ Nhanh Khô Kiểu Dáng Thể Thao The No Style 058 Màu Nâu Đỏ Dáng Vừa Vặn F3', 'ao-khoac-du-03', 'Áo Khoác Dù Phối Màu DurableTex™ Nhanh Khô Kiểu Dáng Thể Thao The No Style 058 Màu Nâu Đỏ Dáng Vừa Vặn F3', 447000, 48, 'images/ao-khoac-du/03.jpg'),
  (84, 17, 'Áo Khoác Dù Phối Màu DurableTex™ Nhanh Khô Kiểu Dáng Thể Thao The No Style 058 Màu Xanh Dương Đen Dáng Vừa Vặn F3', 'ao-khoac-du-04', 'Áo Khoác Dù Phối Màu DurableTex™ Nhanh Khô Kiểu Dáng Thể Thao The No Style 058 Màu Xanh Dương Đen Dáng Vừa Vặn F3', 447000, 49, 'images/ao-khoac-du/04.jpg'),
  (85, 17, 'Áo Khoác Dù Nhẹ DurableTex™ Nhanh Khô Che Nắng Chắn Gió Tiện Lợi Seventy Seven 040 Màu Xanh Dương Đậm Dáng Vừa Vặn F3', 'ao-khoac-du-05', 'Áo Khoác Dù Nhẹ DurableTex™ Nhanh Khô Che Nắng Chắn Gió Tiện Lợi Seventy Seven 040 Màu Xanh Dương Đậm Dáng Vừa Vặn F3', 197000, 50, 'images/ao-khoac-du/05.jpg'),
  (86, 17, 'Áo Khoác Dù Nhẹ DurableTex™ Nhanh Khô Che Nắng Chắn Gió Tiện Lợi Seventy Seven 040 Màu Be Dáng Vừa Vặn F3', 'ao-khoac-du-06', 'Áo Khoác Dù Nhẹ DurableTex™ Nhanh Khô Che Nắng Chắn Gió Tiện Lợi Seventy Seven 040 Màu Be Dáng Vừa Vặn F3', 197000, 51, 'images/ao-khoac-du/06.jpg'),
  (87, 17, 'Áo Khoác Dù Nhẹ DurableTex™ Nhanh Khô Che Nắng Chắn Gió Tiện Lợi Seventy Seven 040 Màu Xám Nhạt Dáng Vừa Vặn F3', 'ao-khoac-du-07', 'Áo Khoác Dù Nhẹ DurableTex™ Nhanh Khô Che Nắng Chắn Gió Tiện Lợi Seventy Seven 040 Màu Xám Nhạt Dáng Vừa Vặn F3', 197000, 52, 'images/ao-khoac-du/07.jpg'),
  (88, 18, 'Quần Đùi Mặc Nhà AirDry™ Vải Mỏng Nhẹ, Thiết Kế Đáy Chữ U Ngồi Bệt Thoải Mái The Homebody 005 Màu Xám Dáng Rộng Rãi F4', 'quan-short-thun-01', 'Quần Đùi Mặc Nhà AirDry™ Vải Mỏng Nhẹ, Thiết Kế Đáy Chữ U Ngồi Bệt Thoải Mái The Homebody 005 Màu Xám Dáng Rộng Rãi F4', 120650, 53, 'images/quan-short-thun/01.jpg'),
  (89, 18, 'Quần Đùi Mặc Nhà AirDry™ Vải Mỏng Nhẹ, Thiết Kế Đáy Chữ U Ngồi Bệt Thoải Mái The Homebody 005 Màu Đen Dáng Rộng Rãi F4', 'quan-short-thun-02', 'Quần Đùi Mặc Nhà AirDry™ Vải Mỏng Nhẹ, Thiết Kế Đáy Chữ U Ngồi Bệt Thoải Mái The Homebody 005 Màu Đen Dáng Rộng Rãi F4', 120650, 54, 'images/quan-short-thun/02.jpg'),
  (90, 18, 'Quần Đùi Mặc Nhà AirDry™ Vải Mỏng Nhẹ, Thiết Kế Đáy Chữ U Dễ Chịu Mọi Tư Thế The Homebody 004 Màu Xám Dáng Rộng Rãi F4', 'quan-short-thun-03', 'Quần Đùi Mặc Nhà AirDry™ Vải Mỏng Nhẹ, Thiết Kế Đáy Chữ U Dễ Chịu Mọi Tư Thế The Homebody 004 Màu Xám Dáng Rộng Rãi F4', 120650, 25, 'images/quan-short-thun/03.jpg'),
  (91, 18, 'Quần Đùi Mặc Nhà AirDry™ Vải Mỏng Nhẹ, Thiết Kế Đáy Chữ U Dễ Chịu Mọi Tư Thế The Homebody 004 Màu Đen Dáng Rộng Rãi F4', 'quan-short-thun-04', 'Quần Đùi Mặc Nhà AirDry™ Vải Mỏng Nhẹ, Thiết Kế Đáy Chữ U Dễ Chịu Mọi Tư Thế The Homebody 004 Màu Đen Dáng Rộng Rãi F4', 120650, 26, 'images/quan-short-thun/04.jpg'),
  (92, 18, 'Quần Đùi Thun Mặc Mát Lạnh IceVibes™ Đáy Mở Rộng Thông Minh Thoải Mái The Minimalist 012 Màu Xám Nhạt Dáng Vừa Vặn F3', 'quan-short-thun-05', 'Quần Đùi Thun Mặc Mát Lạnh IceVibes™ Đáy Mở Rộng Thông Minh Thoải Mái The Minimalist 012 Màu Xám Nhạt Dáng Vừa Vặn F3', 339150, 27, 'images/quan-short-thun/05.jpg'),
  (93, 18, 'Quần Đùi Thun Mặc Mát Lạnh IceVibes™ Đáy Mở Rộng Thông Minh Thoải Mái The Minimalist 012 Màu Xanh Lá Đậm Dáng Vừa Vặn F3', 'quan-short-thun-06', 'Quần Đùi Thun Mặc Mát Lạnh IceVibes™ Đáy Mở Rộng Thông Minh Thoải Mái The Minimalist 012 Màu Xanh Lá Đậm Dáng Vừa Vặn F3', 339150, 28, 'images/quan-short-thun/06.jpg'),
  (94, 18, 'Quần Đùi Thun Mặc Mát Lạnh IceVibes™ Đáy Mở Rộng Thông Minh Thoải Mái The Minimalist 012 Màu Nâu Đậm Dáng Vừa Vặn F3', 'quan-short-thun-07', 'Quần Đùi Thun Mặc Mát Lạnh IceVibes™ Đáy Mở Rộng Thông Minh Thoải Mái The Minimalist 012 Màu Nâu Đậm Dáng Vừa Vặn F3', 339150, 29, 'images/quan-short-thun/07.jpg'),
  (95, 18, 'Quần Đùi Thun Mặc Mát Lạnh IceVibes™ Đáy Mở Rộng Thông Minh Thoải Mái The Minimalist 012 Màu Nâu Nhạt Dáng Vừa Vặn F3', 'quan-short-thun-08', 'Quần Đùi Thun Mặc Mát Lạnh IceVibes™ Đáy Mở Rộng Thông Minh Thoải Mái The Minimalist 012 Màu Nâu Nhạt Dáng Vừa Vặn F3', 339150, 30, 'images/quan-short-thun/08.jpg'),
  (96, 18, 'Quần Đùi Thun Mặc Mát Lạnh IceVibes™ Đáy Mở Rộng Thông Minh Thoải Mái The Minimalist 012 Màu Cam Đậm Dáng Vừa Vặn F3', 'quan-short-thun-09', 'Quần Đùi Thun Mặc Mát Lạnh IceVibes™ Đáy Mở Rộng Thông Minh Thoải Mái The Minimalist 012 Màu Cam Đậm Dáng Vừa Vặn F3', 339150, 31, 'images/quan-short-thun/09.jpg'),
  (97, 18, 'Quần Đùi Thun Mặc Mát Lạnh IceVibes™ Đáy Mở Rộng Thông Minh Thoải Mái The Minimalist 012 Màu Be Dáng Vừa Vặn F3', 'quan-short-thun-10', 'Quần Đùi Thun Mặc Mát Lạnh IceVibes™ Đáy Mở Rộng Thông Minh Thoải Mái The Minimalist 012 Màu Be Dáng Vừa Vặn F3', 339150, 32, 'images/quan-short-thun/10.jpg'),
  (98, 19, 'Quần Đùi Kaki Sọc Trẻ Trung AirDry™ Mịn Mướt Nhẹ Mát The No Style 202 Màu Trắng Xanh Dương Dáng Rộng Rãi F4', 'quan-short-kaki-01', 'Quần Đùi Kaki Sọc Trẻ Trung AirDry™ Mịn Mướt Nhẹ Mát The No Style 202 Màu Trắng Xanh Dương Dáng Rộng Rãi F4', 329650, 33, 'images/quan-short-kaki/01.jpg'),
  (99, 19, 'Quần Đùi Kaki Sọc Trẻ Trung AirDry™ Mịn Mướt Nhẹ Mát The No Style 202 Màu Trắng Xanh Lá Dáng Rộng Rãi F4', 'quan-short-kaki-02', 'Quần Đùi Kaki Sọc Trẻ Trung AirDry™ Mịn Mướt Nhẹ Mát The No Style 202 Màu Trắng Xanh Lá Dáng Rộng Rãi F4', 329650, 34, 'images/quan-short-kaki/02.jpg'),
  (100, 19, 'Quần Đùi Kaki AirDry™ Sợi Rayon Mướt Da The No Style 219 Màu Đen Dáng Rộng Rãi F4', 'quan-short-kaki-03', 'Quần Đùi Kaki AirDry™ Sợi Rayon Mướt Da The No Style 219 Màu Đen Dáng Rộng Rãi F4', 294950, 35, 'images/quan-short-kaki/03.jpg'),
  (101, 19, 'Quần Đùi Kaki AirDry™ Sợi Rayon Mướt Da The No Style 219 Màu Nâu Nhạt Dáng Rộng Rãi F4', 'quan-short-kaki-04', 'Quần Đùi Kaki AirDry™ Sợi Rayon Mướt Da The No Style 219 Màu Nâu Nhạt Dáng Rộng Rãi F4', 294950, 36, 'images/quan-short-kaki/04.jpg'),
  (102, 19, 'Quần Đùi Kaki DurableTex™ Dây Rút Ẩn Tự Thu Nhỏ Vòng Lưng The Weekend 030 Màu Xanh Dương Đậm Dáng Rộng Rãi F4', 'quan-short-kaki-05', 'Quần Đùi Kaki DurableTex™ Dây Rút Ẩn Tự Thu Nhỏ Vòng Lưng The Weekend 030 Màu Xanh Dương Đậm Dáng Rộng Rãi F4', 339150, 37, 'images/quan-short-kaki/05.jpg'),
  (103, 19, 'Quần Đùi Kaki DurableTex™ Dây Rút Ẩn Tự Thu Nhỏ Vòng Lưng The Weekend 030 Màu Xanh Lá Đậm Dáng Rộng Rãi F4', 'quan-short-kaki-06', 'Quần Đùi Kaki DurableTex™ Dây Rút Ẩn Tự Thu Nhỏ Vòng Lưng The Weekend 030 Màu Xanh Lá Đậm Dáng Rộng Rãi F4', 339150, 38, 'images/quan-short-kaki/06.jpg'),
  (104, 19, 'Quần Đùi Kaki DurableTex™ Dây Rút Ẩn Tự Thu Nhỏ Vòng Lưng The Weekend 030 Màu Nâu Nhạt Dáng Rộng Rãi F4', 'quan-short-kaki-07', 'Quần Đùi Kaki DurableTex™ Dây Rút Ẩn Tự Thu Nhỏ Vòng Lưng The Weekend 030 Màu Nâu Nhạt Dáng Rộng Rãi F4', 339150, 39, 'images/quan-short-kaki/07.jpg'),
  (105, 19, 'Quần Đùi Kaki DurableTex™ Dây Rút Ẩn Tự Thu Nhỏ Vòng Lưng The Weekend 030 Màu Xám Dáng Rộng Rãi F4', 'quan-short-kaki-08', 'Quần Đùi Kaki DurableTex™ Dây Rút Ẩn Tự Thu Nhỏ Vòng Lưng The Weekend 030 Màu Xám Dáng Rộng Rãi F4', 339150, 40, 'images/quan-short-kaki/08.jpg'),
  (106, 19, 'Quần Đùi Kaki DurableTex™ Dây Rút Ẩn Tự Thu Nhỏ Vòng Lưng The Weekend 030 Màu Đen Dáng Rộng Rãi F4', 'quan-short-kaki-09', 'Quần Đùi Kaki DurableTex™ Dây Rút Ẩn Tự Thu Nhỏ Vòng Lưng The Weekend 030 Màu Đen Dáng Rộng Rãi F4', 339150, 41, 'images/quan-short-kaki/09.jpg'),
  (107, 19, 'Quần Đùi Vải Nhung Mềm Mịn Tay Lưng Thun Seventy Seven 032 Màu Xanh Lá Đậm Dáng Rộng Rãi F4', 'quan-short-kaki-10', 'Quần Đùi Vải Nhung Mềm Mịn Tay Lưng Thun Seventy Seven 032 Màu Xanh Lá Đậm Dáng Rộng Rãi F4', 147000, 42, 'images/quan-short-kaki/10.jpg'),
  (108, 20, 'Quần Tây Thanh Lịch DurableTex™ Vải Đanh Chắc Mặc Bền The Minimalist 011 Màu Nâu Nhạt Dáng Vừa Vặn F3', 'quan-tay-01', 'Quần Tây Thanh Lịch DurableTex™ Vải Đanh Chắc Mặc Bền The Minimalist 011 Màu Nâu Nhạt Dáng Vừa Vặn F3', 472150, 43, 'images/quan-tay/01.jpg'),
  (109, 20, 'Quần Tây Thanh Lịch DurableTex™ Vải Đanh Chắc Mặc Bền The Minimalist 011 Màu Đen Dáng Vừa Vặn F3', 'quan-tay-02', 'Quần Tây Thanh Lịch DurableTex™ Vải Đanh Chắc Mặc Bền The Minimalist 011 Màu Đen Dáng Vừa Vặn F3', 472150, 44, 'images/quan-tay/02.jpg'),
  (110, 20, 'Quần Tây Trẻ Trung EasyCare™ Ít Nhăn, Đai Hông Nới Rộng Chống Tức Bụng The CEO 017 Màu Đen Dáng Ôm Vừa F2', 'quan-tay-03', 'Quần Tây Trẻ Trung EasyCare™ Ít Nhăn, Đai Hông Nới Rộng Chống Tức Bụng The CEO 017 Màu Đen Dáng Ôm Vừa F2', 472150, 45, 'images/quan-tay/03.jpg'),
  (111, 20, 'Quần Tây Trẻ Trung EasyCare™ Vải Mềm Mặc Mát, Đai Hông Nới Rộng Chống Tức Bụng The CEO 012 Màu Xám Đậm Dáng Ôm Vừa F2', 'quan-tay-04', 'Quần Tây Trẻ Trung EasyCare™ Vải Mềm Mặc Mát, Đai Hông Nới Rộng Chống Tức Bụng The CEO 012 Màu Xám Đậm Dáng Ôm Vừa F2', 472150, 46, 'images/quan-tay/04.jpg'),
  (112, 20, 'Quần Tây Sợi Rayon Mướt Da EasyCare™ Lâu Nhăn, Đai Hông Nới Rộng Không Cần Thắt Lưng The CEO 015 Màu Đen Dáng Ôm Vừa F2', 'quan-tay-05', 'Quần Tây Sợi Rayon Mướt Da EasyCare™ Lâu Nhăn, Đai Hông Nới Rộng Không Cần Thắt Lưng The CEO 015 Màu Đen Dáng Ôm Vừa F2', 472150, 47, 'images/quan-tay/05.jpg'),
  (113, 20, 'Quần Tây Sợi Rayon Mướt Da EasyCare™ Ít Nhăn Lưng Thun Co Giãn Non Iron 001 Màu Xám Nhạt Dáng Ôm Vừa F2', 'quan-tay-06', 'Quần Tây Sợi Rayon Mướt Da EasyCare™ Ít Nhăn Lưng Thun Co Giãn Non Iron 001 Màu Xám Nhạt Dáng Ôm Vừa F2', 297000, 48, 'images/quan-tay/06.jpg'),
  (114, 20, 'Quần Tây Sợi Rayon Mướt Da EasyCare™ Ít Nhăn Lưng Thun Co Giãn Non Iron 001 Màu Be Dáng Ôm Vừa F2', 'quan-tay-07', 'Quần Tây Sợi Rayon Mướt Da EasyCare™ Ít Nhăn Lưng Thun Co Giãn Non Iron 001 Màu Be Dáng Ôm Vừa F2', 297000, 49, 'images/quan-tay/07.jpg'),
  (115, 20, 'Quần Tây Sợi Rayon Mướt Da EasyCare™ Ít Nhăn Lưng Thun Co Giãn Non Iron 001 Màu Đen Dáng Ôm Vừa F2', 'quan-tay-08', 'Quần Tây Sợi Rayon Mướt Da EasyCare™ Ít Nhăn Lưng Thun Co Giãn Non Iron 001 Màu Đen Dáng Ôm Vừa F2', 297000, 50, 'images/quan-tay/08.jpg'),
  (116, 20, 'Quần Tây Sợi Rayon Mướt Da EasyCare™ Ít Nhăn Lưng Thun Co Giãn Non Iron 001 Màu Nâu Dáng Ôm Vừa F2', 'quan-tay-09', 'Quần Tây Sợi Rayon Mướt Da EasyCare™ Ít Nhăn Lưng Thun Co Giãn Non Iron 001 Màu Nâu Dáng Ôm Vừa F2', 297000, 51, 'images/quan-tay/09.jpg'),
  (117, 20, 'Quần Tây Kiểu Cơ Bản Dễ Phối Đồ EasyCare™ Bền Màu Giặt Ít Nhăn Non Branded 030 Màu Be Dáng Ôm Vừa F2', 'quan-tay-10', 'Quần Tây Kiểu Cơ Bản Dễ Phối Đồ EasyCare™ Bền Màu Giặt Ít Nhăn Non Branded 030 Màu Be Dáng Ôm Vừa F2', 377150, 52, 'images/quan-tay/10.jpg'),
  (118, 21, 'Quần Kaki The Minimalist 016 Vải Siêu Bền, Lưng Thun Ẩn, Đáy Thông Minh Màu Xám Đậm Dáng Vừa Vặn F3', 'quan-kaki-01', 'Quần Kaki The Minimalist 016 Vải Siêu Bền, Lưng Thun Ẩn, Đáy Thông Minh Màu Xám Đậm Dáng Vừa Vặn F3', 472150, 53, 'images/quan-kaki/01.jpg'),
  (119, 21, 'Quần Kaki The Minimalist 016 Vải Siêu Bền, Lưng Thun Ẩn, Đáy Thông Minh Màu Đen Dáng Vừa Vặn F3', 'quan-kaki-02', 'Quần Kaki The Minimalist 016 Vải Siêu Bền, Lưng Thun Ẩn, Đáy Thông Minh Màu Đen Dáng Vừa Vặn F3', 472150, 54, 'images/quan-kaki/02.jpg'),
  (120, 21, 'Quần Kaki Ống Rộng DurableTex™ Vải Dày Dặn, Xếp Ly Che Khuyết Điểm The No Style 242 Màu Nâu Dáng Rộng Rãi F4', 'quan-kaki-03', 'Quần Kaki Ống Rộng DurableTex™ Vải Dày Dặn, Xếp Ly Che Khuyết Điểm The No Style 242 Màu Nâu Dáng Rộng Rãi F4', 472150, 25, 'images/quan-kaki/03.jpg'),
  (121, 21, 'Quần Kaki Ống Rộng DurableTex™ Vải Dày Dặn, Xếp Ly Che Khuyết Điểm The No Style 242 Màu Nâu Đậm Dáng Rộng Rãi F4', 'quan-kaki-04', 'Quần Kaki Ống Rộng DurableTex™ Vải Dày Dặn, Xếp Ly Che Khuyết Điểm The No Style 242 Màu Nâu Đậm Dáng Rộng Rãi F4', 472150, 26, 'images/quan-kaki/04.jpg'),
  (122, 21, 'Quần Kaki CloudTouch™ Vải Mềm Êm Da, Đáy Mở Rộng Thông Minh The Minimalist 018 Màu Xanh Dương Đậm Dáng Vừa Vặn F3', 'quan-kaki-05', 'Quần Kaki CloudTouch™ Vải Mềm Êm Da, Đáy Mở Rộng Thông Minh The Minimalist 018 Màu Xanh Dương Đậm Dáng Vừa Vặn F3', 434150, 27, 'images/quan-kaki/05.jpg'),
  (123, 21, 'Quần Kaki CloudTouch™ Vải Mềm Êm Da, Đáy Mở Rộng Thông Minh The Minimalist 018 Màu Đen Dáng Vừa Vặn F3', 'quan-kaki-06', 'Quần Kaki CloudTouch™ Vải Mềm Êm Da, Đáy Mở Rộng Thông Minh The Minimalist 018 Màu Đen Dáng Vừa Vặn F3', 434150, 28, 'images/quan-kaki/06.jpg'),
  (124, 21, 'Quần Kaki DurableTex™ Vải Dai Chắc, Đầu Gối Xếp Ly Co Gập Thoải Mái The Worker 009 Màu Xám Đậm Dáng Vừa Vặn F3', 'quan-kaki-07', 'Quần Kaki DurableTex™ Vải Dai Chắc, Đầu Gối Xếp Ly Co Gập Thoải Mái The Worker 009 Màu Xám Đậm Dáng Vừa Vặn F3', 548150, 29, 'images/quan-kaki/07.jpg'),
  (125, 21, 'Quần Kaki DurableTex™ Vải Dai Chắc, Đầu Gối Xếp Ly Co Gập Thoải Mái The Worker 009 Màu Xanh Lá Đậm Dáng Vừa Vặn F3', 'quan-kaki-08', 'Quần Kaki DurableTex™ Vải Dai Chắc, Đầu Gối Xếp Ly Co Gập Thoải Mái The Worker 009 Màu Xanh Lá Đậm Dáng Vừa Vặn F3', 548150, 30, 'images/quan-kaki/08.jpg'),
  (126, 21, 'Quần Kaki DurableTex™ Vải Dày Dặn Sờ Êm Tay Non Branded 055 Màu Nâu Dáng Ôm Vừa F2', 'quan-kaki-09', 'Quần Kaki DurableTex™ Vải Dày Dặn Sờ Êm Tay Non Branded 055 Màu Nâu Dáng Ôm Vừa F2', 472150, 31, 'images/quan-kaki/09.jpg'),
  (127, 21, 'Quần Kaki DurableTex™ Vải Dày Dặn Sờ Êm Tay Non Branded 055 Màu Xám Dáng Ôm Vừa F2', 'quan-kaki-10', 'Quần Kaki DurableTex™ Vải Dày Dặn Sờ Êm Tay Non Branded 055 Màu Xám Dáng Ôm Vừa F2', 472150, 32, 'images/quan-kaki/10.jpg'),
  (128, 22, 'Quần Jean Sợi Cà Phê S.Café® StayFresh™ Thoát Ẩm Nhanh Khử Mùi The Original 040 Màu Xanh Dương Nhạt Dáng Ôm Vừa F2', 'quan-jeans-slimfit-01', 'Quần Jean Sợi Cà Phê S.Café® StayFresh™ Thoát Ẩm Nhanh Khử Mùi The Original 040 Màu Xanh Dương Nhạt Dáng Ôm Vừa F2', 472150, 33, 'images/quan-jeans-slimfit/01.jpg'),
  (129, 22, 'Quần Jean Sợi Cà Phê S.Café® StayFresh™ Thoát Ẩm Nhanh Khử Mùi The Original 040 Màu Xanh Dương Dáng Ôm Vừa F2', 'quan-jeans-slimfit-02', 'Quần Jean Sợi Cà Phê S.Café® StayFresh™ Thoát Ẩm Nhanh Khử Mùi The Original 040 Màu Xanh Dương Dáng Ôm Vừa F2', 472150, 34, 'images/quan-jeans-slimfit/02.jpg'),
  (130, 22, 'Quần Jean Sợi Cà Phê S.Café® StayFresh™ Thoát Ẩm Nhanh Khử Mùi The Original 040 Màu Xanh Dương Đậm Dáng Ôm Vừa F2', 'quan-jeans-slimfit-03', 'Quần Jean Sợi Cà Phê S.Café® StayFresh™ Thoát Ẩm Nhanh Khử Mùi The Original 040 Màu Xanh Dương Đậm Dáng Ôm Vừa F2', 422450, 35, 'images/quan-jeans-slimfit/03.jpg'),
  (131, 22, 'Quần Jean Sợi Coolmax® IceVibes™ Vải Mềm Thấm Hút Tốt Hạ Nhiệt Nhanh The Original 007 Màu Xanh Dương Dáng Ôm Vừa F2', 'quan-jeans-slimfit-04', 'Quần Jean Sợi Coolmax® IceVibes™ Vải Mềm Thấm Hút Tốt Hạ Nhiệt Nhanh The Original 007 Màu Xanh Dương Dáng Ôm Vừa F2', 529150, 36, 'images/quan-jeans-slimfit/04.jpg'),
  (132, 22, 'Quần Jean Sợi Coolmax® IceVibes™ Vải Mềm Thấm Hút Tốt Hạ Nhiệt Nhanh The Original 007 Màu Xanh Dương Đậm Dáng Ôm Vừa F2', 'quan-jeans-slimfit-05', 'Quần Jean Sợi Coolmax® IceVibes™ Vải Mềm Thấm Hút Tốt Hạ Nhiệt Nhanh The Original 007 Màu Xanh Dương Đậm Dáng Ôm Vừa F2', 529150, 37, 'images/quan-jeans-slimfit/05.jpg'),
  (133, 22, 'Quần Jean Sợi Coolmax® IceVibes™ Vải Mềm Thấm Hút Tốt Hạ Nhiệt Nhanh The Original 007 Màu Xanh Dương Nhạt Dáng Ôm Vừa F2', 'quan-jeans-slimfit-06', 'Quần Jean Sợi Coolmax® IceVibes™ Vải Mềm Thấm Hút Tốt Hạ Nhiệt Nhanh The Original 007 Màu Xanh Dương Nhạt Dáng Ôm Vừa F2', 529150, 38, 'images/quan-jeans-slimfit/06.jpg'),
  (134, 22, 'Quần Jean ColorLock™ Giữ Màu Đen Sâu Lâu Bạc Màu Tek Black Jean 004 Màu Đen Dáng Ôm Vừa F2', 'quan-jeans-slimfit-07', 'Quần Jean ColorLock™ Giữ Màu Đen Sâu Lâu Bạc Màu Tek Black Jean 004 Màu Đen Dáng Ôm Vừa F2', 453150, 39, 'images/quan-jeans-slimfit/07.jpg'),
  (135, 22, 'Quần Jean FlexFit™ Rách Gối Bụi Bặm Vải Mềm Mướt Co Giãn The Original 009 Màu Xanh Dương Nhạt Dáng Ôm Vừa F2', 'quan-jeans-slimfit-08', 'Quần Jean FlexFit™ Rách Gối Bụi Bặm Vải Mềm Mướt Co Giãn The Original 009 Màu Xanh Dương Nhạt Dáng Ôm Vừa F2', 228500, 40, 'images/quan-jeans-slimfit/08.jpg'),
  (136, 22, 'Quần Jean FlexFit™ Rách Gối Bụi Bặm Vải Mềm Mướt Co Giãn The Original 009 Màu Xanh Dương Đậm Dáng Ôm Vừa F2', 'quan-jeans-slimfit-09', 'Quần Jean FlexFit™ Rách Gối Bụi Bặm Vải Mềm Mướt Co Giãn The Original 009 Màu Xanh Dương Đậm Dáng Ôm Vừa F2', 228500, 41, 'images/quan-jeans-slimfit/09.jpg'),
  (137, 22, 'Quần Jean FlexFit™ Rách Gối Bụi Bặm Vải Mềm Mướt Co Giãn The Original 009 Màu Xanh Dương Dáng Ôm Vừa F2', 'quan-jeans-slimfit-10', 'Quần Jean FlexFit™ Rách Gối Bụi Bặm Vải Mềm Mướt Co Giãn The Original 009 Màu Xanh Dương Dáng Ôm Vừa F2', 228500, 42, 'images/quan-jeans-slimfit/10.jpg'),
  (138, 23, 'Quần Jeans Baggy Ống Cong 3D Giải Phóng Đôi Chân DurableTex™ The Original 053 Màu Xanh Jean 87 Dáng Siêu Rộng F5', 'quan-jeans-loose-fit-01', 'Quần Jeans Baggy Ống Cong 3D Giải Phóng Đôi Chân DurableTex™ The Original 053 Màu Xanh Jean 87 Dáng Siêu Rộng F5', 472150, 43, 'images/quan-jeans-loose-fit/01.jpg'),
  (139, 23, 'Quần Jeans Baggy Ống Cong 3D Giải Phóng Đôi Chân DurableTex™ The Original 053 Màu Xanh Jean 89 Dáng Siêu Rộng F5', 'quan-jeans-loose-fit-02', 'Quần Jeans Baggy Ống Cong 3D Giải Phóng Đôi Chân DurableTex™ The Original 053 Màu Xanh Jean 89 Dáng Siêu Rộng F5', 472150, 44, 'images/quan-jeans-loose-fit/02.jpg'),
  (140, 23, 'Quần Jean Suông Rộng DurableTex™ Đắp 2 Lớp Chống Rách Gối Siêu Bền Multi Color Jean 012 Màu Nâu Nhạt Dáng Rộng Rãi F4', 'quan-jeans-loose-fit-03', 'Quần Jean Suông Rộng DurableTex™ Đắp 2 Lớp Chống Rách Gối Siêu Bền Multi Color Jean 012 Màu Nâu Nhạt Dáng Rộng Rãi F4', 529150, 45, 'images/quan-jeans-loose-fit/03.jpg'),
  (141, 23, 'Quần Jean Suông Rộng DurableTex™ Đắp 2 Lớp Chống Rách Gối Siêu Bền Multi Color Jean 012 Màu Xanh Lá Đậm Dáng Rộng Rãi F4', 'quan-jeans-loose-fit-04', 'Quần Jean Suông Rộng DurableTex™ Đắp 2 Lớp Chống Rách Gối Siêu Bền Multi Color Jean 012 Màu Xanh Lá Đậm Dáng Rộng Rãi F4', 529150, 46, 'images/quan-jeans-loose-fit/04.jpg'),
  (142, 23, 'Quần Jean Suông Rộng DurableTex™ Đắp 2 Lớp Chống Rách Gối Siêu Bền Multi Color Jean 012 Màu Đen Dáng Rộng Rãi F4', 'quan-jeans-loose-fit-05', 'Quần Jean Suông Rộng DurableTex™ Đắp 2 Lớp Chống Rách Gối Siêu Bền Multi Color Jean 012 Màu Đen Dáng Rộng Rãi F4', 529150, 47, 'images/quan-jeans-loose-fit/05.jpg'),
  (143, 23, 'Quần Jean Suông Rộng DurableTex™ Đắp 2 Lớp Chống Rách Gối Siêu Bền Multi Color Jean 012 Màu Nâu Đậm Dáng Rộng Rãi F4', 'quan-jeans-loose-fit-06', 'Quần Jean Suông Rộng DurableTex™ Đắp 2 Lớp Chống Rách Gối Siêu Bền Multi Color Jean 012 Màu Nâu Đậm Dáng Rộng Rãi F4', 529150, 48, 'images/quan-jeans-loose-fit/06.jpg'),
  (144, 23, 'Quần Jean Suông Rộng DurableTex™ Đắp 2 Lớp Chống Rách Gối Siêu Bền Multi Color Jean 012 Màu Xám Dáng Rộng Rãi F4', 'quan-jeans-loose-fit-07', 'Quần Jean Suông Rộng DurableTex™ Đắp 2 Lớp Chống Rách Gối Siêu Bền Multi Color Jean 012 Màu Xám Dáng Rộng Rãi F4', 529150, 49, 'images/quan-jeans-loose-fit/07.jpg'),
  (145, 23, 'Quần Jean Che Khuyết Điểm DurableTex™ Dày Dặn Mặc Thoát Mồ Hôi The Original 038 Màu Xanh Dương Nhạt Dáng Rộng Rãi F4', 'quan-jeans-loose-fit-08', 'Quần Jean Che Khuyết Điểm DurableTex™ Dày Dặn Mặc Thoát Mồ Hôi The Original 038 Màu Xanh Dương Nhạt Dáng Rộng Rãi F4', 377150, 50, 'images/quan-jeans-loose-fit/08.jpg'),
  (146, 23, 'Quần Jean Che Khuyết Điểm DurableTex™ Dày Dặn Mặc Thoát Mồ Hôi The Original 038 Màu Xanh Dương Dáng Rộng Rãi F4', 'quan-jeans-loose-fit-09', 'Quần Jean Che Khuyết Điểm DurableTex™ Dày Dặn Mặc Thoát Mồ Hôi The Original 038 Màu Xanh Dương Dáng Rộng Rãi F4', 377150, 51, 'images/quan-jeans-loose-fit/09.jpg'),
  (147, 23, 'Quần Jean Che Khuyết Điểm DurableTex™ Dày Dặn Mặc Thoát Mồ Hôi The Original 038 Màu Xanh Dương Đậm Dáng Rộng Rãi F4', 'quan-jeans-loose-fit-10', 'Quần Jean Che Khuyết Điểm DurableTex™ Dày Dặn Mặc Thoát Mồ Hôi The Original 038 Màu Xanh Dương Đậm Dáng Rộng Rãi F4', 377150, 52, 'images/quan-jeans-loose-fit/10.jpg'),
  (148, 24, 'Giày Tây Oxford Real Leather 007 Đen', 'giay-oxford-01', 'Giày Tây Oxford Real Leather 007 Đen', 480900, 53, 'images/giay-oxford/01.jpg'),
  (149, 24, 'Giày Tây Oxford Real Leather 004 Đen', 'giay-oxford-02', 'Giày Tây Oxford Real Leather 004 Đen', 480900, 54, 'images/giay-oxford/02.jpg'),
  (150, 24, 'Giày Tây Oxford Real Leather 003 Đen', 'giay-oxford-03', 'Giày Tây Oxford Real Leather 003 Đen', 480900, 25, 'images/giay-oxford/03.jpg'),
  (151, 25, 'Giày Tây Loafer Real Leather 006 Đen', 'giay-loafer-01', 'Giày Tây Loafer Real Leather 006 Đen', 529900, 26, 'images/giay-loafer/01.jpg'),
  (152, 25, 'Giày Tây Loafer Real Leather 005 Đen', 'giay-loafer-02', 'Giày Tây Loafer Real Leather 005 Đen', 480900, 27, 'images/giay-loafer/02.jpg'),
  (153, 25, 'Giày Tây Loafer Real Leather 002 Đen', 'giay-loafer-03', 'Giày Tây Loafer Real Leather 002 Đen', 480900, 28, 'images/giay-loafer/03.jpg'),
  (154, 26, 'Giày Boots Real Leather 001 Đen', 'giay-boots-01', 'Giày Boots Real Leather 001 Đen', 627900, 29, 'images/giay-boots/01.jpg');

INSERT INTO product_images (product_id, image_path, sort_order) VALUES
  (1, 'images/ao-thun-co-tron-tay-ngan/01.jpg', 1),
  (2, 'images/ao-thun-co-tron-tay-ngan/02.jpg', 1),
  (3, 'images/ao-thun-co-tron-tay-ngan/03.jpg', 1),
  (4, 'images/ao-thun-co-tron-tay-ngan/04.jpg', 1),
  (5, 'images/ao-thun-co-tron-tay-ngan/05.jpg', 1),
  (6, 'images/ao-thun-co-tron-tay-ngan/06.jpg', 1),
  (7, 'images/ao-thun-co-tron-tay-ngan/07.jpg', 1),
  (8, 'images/ao-thun-co-tron-tay-ngan/08.jpg', 1),
  (9, 'images/ao-thun-co-tron-tay-ngan/09.jpg', 1),
  (10, 'images/ao-thun-co-tron-tay-ngan/10.jpg', 1),
  (11, 'images/ao-thun-tay-dai/01.jpg', 1),
  (12, 'images/ao-thun-tay-dai/02.jpg', 1),
  (13, 'images/ao-thun-tay-dai/03.jpg', 1),
  (14, 'images/ao-thun-tay-dai/04.jpg', 1),
  (15, 'images/ao-thun-tay-dai/05.jpg', 1),
  (16, 'images/ao-thun-tay-dai/06.jpg', 1),
  (17, 'images/ao-thun-tay-dai/07.jpg', 1),
  (18, 'images/ao-thun-tay-dai/08.jpg', 1),
  (19, 'images/ao-thun-tay-dai/09.jpg', 1),
  (20, 'images/ao-thun-tay-dai/10.jpg', 1),
  (21, 'images/ao-thun-co-polo-tay-ngan/01.jpg', 1),
  (22, 'images/ao-thun-co-polo-tay-ngan/02.jpg', 1),
  (23, 'images/ao-thun-co-polo-tay-ngan/03.jpg', 1),
  (24, 'images/ao-thun-co-polo-tay-ngan/04.jpg', 1),
  (25, 'images/ao-thun-co-polo-tay-ngan/05.jpg', 1),
  (26, 'images/ao-thun-co-polo-tay-ngan/06.jpg', 1),
  (27, 'images/ao-thun-co-polo-tay-ngan/07.jpg', 1),
  (28, 'images/ao-thun-co-polo-tay-ngan/08.jpg', 1),
  (29, 'images/ao-thun-co-polo-tay-ngan/09.jpg', 1),
  (30, 'images/ao-thun-co-polo-tay-ngan/10.jpg', 1),
  (31, 'images/ao-thun-polo-tay-dai/01.jpg', 1),
  (32, 'images/ao-thun-polo-tay-dai/02.jpg', 1),
  (33, 'images/ao-thun-polo-tay-dai/03.jpg', 1),
  (34, 'images/ao-thun-polo-tay-dai/04.jpg', 1),
  (35, 'images/ao-thun-polo-tay-dai/05.jpg', 1),
  (36, 'images/ao-thun-polo-tay-dai/06.jpg', 1),
  (37, 'images/ao-thun-polo-tay-dai/07.jpg', 1),
  (38, 'images/ao-thun-polo-tay-dai/08.jpg', 1),
  (39, 'images/ao-thun-polo-tay-dai/09.jpg', 1),
  (40, 'images/ao-thun-polo-tay-dai/10.jpg', 1),
  (41, 'images/ao-so-mi-tay-ngan/01.jpg', 1),
  (42, 'images/ao-so-mi-tay-ngan/02.jpg', 1),
  (43, 'images/ao-so-mi-tay-ngan/03.jpg', 1),
  (44, 'images/ao-so-mi-tay-ngan/04.jpg', 1),
  (45, 'images/ao-so-mi-tay-ngan/05.jpg', 1),
  (46, 'images/ao-so-mi-tay-ngan/06.jpg', 1),
  (47, 'images/ao-so-mi-tay-ngan/07.jpg', 1),
  (48, 'images/ao-so-mi-tay-ngan/08.jpg', 1),
  (49, 'images/ao-so-mi-tay-ngan/09.jpg', 1),
  (50, 'images/ao-so-mi-tay-ngan/10.jpg', 1),
  (51, 'images/ao-so-mi-tay-dai/01.jpg', 1),
  (52, 'images/ao-so-mi-tay-dai/02.jpg', 1),
  (53, 'images/ao-so-mi-tay-dai/03.jpg', 1),
  (54, 'images/ao-so-mi-tay-dai/04.jpg', 1),
  (55, 'images/ao-so-mi-tay-dai/05.jpg', 1),
  (56, 'images/ao-so-mi-tay-dai/06.jpg', 1),
  (57, 'images/ao-so-mi-tay-dai/07.jpg', 1),
  (58, 'images/ao-so-mi-tay-dai/08.jpg', 1),
  (59, 'images/ao-so-mi-tay-dai/09.jpg', 1),
  (60, 'images/ao-so-mi-tay-dai/10.jpg', 1),
  (61, 'images/ao-khoac-jean/01.jpg', 1),
  (62, 'images/ao-khoac-jean/02.jpg', 1),
  (63, 'images/ao-khoac-jean/03.jpg', 1),
  (64, 'images/ao-khoac-jean/04.jpg', 1),
  (65, 'images/ao-khoac-jean/05.jpg', 1),
  (66, 'images/ao-khoac-jean/06.jpg', 1),
  (67, 'images/ao-khoac-jean/07.jpg', 1),
  (68, 'images/ao-khoac-jean/08.jpg', 1),
  (69, 'images/ao-khoac-jean/09.jpg', 1),
  (70, 'images/ao-khoac-jean/10.jpg', 1),
  (71, 'images/ao-khoac-kaki/01.jpg', 1),
  (72, 'images/ao-khoac-kaki/02.jpg', 1),
  (73, 'images/ao-khoac-kaki/03.jpg', 1),
  (74, 'images/ao-khoac-kaki/04.jpg', 1),
  (75, 'images/ao-khoac-kaki/05.jpg', 1),
  (76, 'images/ao-khoac-kaki/06.jpg', 1),
  (77, 'images/ao-khoac-kaki/07.jpg', 1),
  (78, 'images/ao-khoac-kaki/08.jpg', 1),
  (79, 'images/ao-khoac-kaki/09.jpg', 1),
  (80, 'images/ao-khoac-kaki/10.jpg', 1),
  (81, 'images/ao-khoac-du/01.jpg', 1),
  (82, 'images/ao-khoac-du/02.jpg', 1),
  (83, 'images/ao-khoac-du/03.jpg', 1),
  (84, 'images/ao-khoac-du/04.jpg', 1),
  (85, 'images/ao-khoac-du/05.jpg', 1),
  (86, 'images/ao-khoac-du/06.jpg', 1),
  (87, 'images/ao-khoac-du/07.jpg', 1),
  (88, 'images/quan-short-thun/01.jpg', 1),
  (89, 'images/quan-short-thun/02.jpg', 1),
  (90, 'images/quan-short-thun/03.jpg', 1),
  (91, 'images/quan-short-thun/04.jpg', 1),
  (92, 'images/quan-short-thun/05.jpg', 1),
  (93, 'images/quan-short-thun/06.jpg', 1),
  (94, 'images/quan-short-thun/07.jpg', 1),
  (95, 'images/quan-short-thun/08.jpg', 1),
  (96, 'images/quan-short-thun/09.jpg', 1),
  (97, 'images/quan-short-thun/10.jpg', 1),
  (98, 'images/quan-short-kaki/01.jpg', 1),
  (99, 'images/quan-short-kaki/02.jpg', 1),
  (100, 'images/quan-short-kaki/03.jpg', 1),
  (101, 'images/quan-short-kaki/04.jpg', 1),
  (102, 'images/quan-short-kaki/05.jpg', 1),
  (103, 'images/quan-short-kaki/06.jpg', 1),
  (104, 'images/quan-short-kaki/07.jpg', 1),
  (105, 'images/quan-short-kaki/08.jpg', 1),
  (106, 'images/quan-short-kaki/09.jpg', 1),
  (107, 'images/quan-short-kaki/10.jpg', 1),
  (108, 'images/quan-tay/01.jpg', 1),
  (109, 'images/quan-tay/02.jpg', 1),
  (110, 'images/quan-tay/03.jpg', 1),
  (111, 'images/quan-tay/04.jpg', 1),
  (112, 'images/quan-tay/05.jpg', 1),
  (113, 'images/quan-tay/06.jpg', 1),
  (114, 'images/quan-tay/07.jpg', 1),
  (115, 'images/quan-tay/08.jpg', 1),
  (116, 'images/quan-tay/09.jpg', 1),
  (117, 'images/quan-tay/10.jpg', 1),
  (118, 'images/quan-kaki/01.jpg', 1),
  (119, 'images/quan-kaki/02.jpg', 1),
  (120, 'images/quan-kaki/03.jpg', 1),
  (121, 'images/quan-kaki/04.jpg', 1),
  (122, 'images/quan-kaki/05.jpg', 1),
  (123, 'images/quan-kaki/06.jpg', 1),
  (124, 'images/quan-kaki/07.jpg', 1),
  (125, 'images/quan-kaki/08.jpg', 1),
  (126, 'images/quan-kaki/09.jpg', 1),
  (127, 'images/quan-kaki/10.jpg', 1),
  (128, 'images/quan-jeans-slimfit/01.jpg', 1),
  (129, 'images/quan-jeans-slimfit/02.jpg', 1),
  (130, 'images/quan-jeans-slimfit/03.jpg', 1),
  (131, 'images/quan-jeans-slimfit/04.jpg', 1),
  (132, 'images/quan-jeans-slimfit/05.jpg', 1),
  (133, 'images/quan-jeans-slimfit/06.jpg', 1),
  (134, 'images/quan-jeans-slimfit/07.jpg', 1),
  (135, 'images/quan-jeans-slimfit/08.jpg', 1),
  (136, 'images/quan-jeans-slimfit/09.jpg', 1),
  (137, 'images/quan-jeans-slimfit/10.jpg', 1),
  (138, 'images/quan-jeans-loose-fit/01.jpg', 1),
  (139, 'images/quan-jeans-loose-fit/02.jpg', 1),
  (140, 'images/quan-jeans-loose-fit/03.jpg', 1),
  (141, 'images/quan-jeans-loose-fit/04.jpg', 1),
  (142, 'images/quan-jeans-loose-fit/05.jpg', 1),
  (143, 'images/quan-jeans-loose-fit/06.jpg', 1),
  (144, 'images/quan-jeans-loose-fit/07.jpg', 1),
  (145, 'images/quan-jeans-loose-fit/08.jpg', 1),
  (146, 'images/quan-jeans-loose-fit/09.jpg', 1),
  (147, 'images/quan-jeans-loose-fit/10.jpg', 1),
  (148, 'images/giay-oxford/01.jpg', 1),
  (149, 'images/giay-oxford/02.jpg', 1),
  (150, 'images/giay-oxford/03.jpg', 1),
  (151, 'images/giay-loafer/01.jpg', 1),
  (152, 'images/giay-loafer/02.jpg', 1),
  (153, 'images/giay-loafer/03.jpg', 1),
  (154, 'images/giay-boots/01.jpg', 1);
